backend:
  name: turbo-github
  turbo_site_id: 53877c38-a47b-4a7a-aee1-a25f0f470ee3
  branch: main
media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Capa", name: "image", widget: "image", required: false }
      - { label: "Resumo", name: "description", widget: "text", required: false }
      - { label: "Corpo", name: "body", widget: "markdown" }
