backend:
  name: turbo-github
  turbo_site_id: ff7cc77e-c75c-4adc-9603-405fa6050fe9
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Capa", name: "image", widget: "image", required: false }
      - { label: "Resumo", name: "description", widget: "text", required: false }
      - { label: "Corpo", name: "body", widget: "markdown" }
